project_id = "seztdbhanafqiknypiae"

[functions.create-magic-link]
verify_jwt = true

[functions.validate-magic-link]
verify_jwt = false

[functions.submit-evidence]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.daily-expirations-job]
verify_jwt = true

[functions.export-audit]
verify_jwt = true

[functions.send-demo-email]
verify_jwt = true

[functions.analyze-document]
verify_jwt = true

[functions.log-audit]
verify_jwt = true
